---
# set non default kernel parameters for network
- name: Copy configuration file to /etc/sysctl.d/99-custom-network-harden.conf
  template:
    src: "etc/99-custom-network-harden-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.conf"
    dest: /etc/sysctl.d/99-custom-network-harden.conf
    owner: root
    group: root
    mode: 0644
  when:
    - set_network_parameters

- name: "Ensure wireless interfaces are disabled"
  block:
    - name: "Ensure wireless interfaces are disabled | Check if nmcli command is available"
      command: rpm -q NetworkManager
      changed_when: false
      failed_when: false
      check_mode: false
      args:
        warn: false
      register: rhel_nmcli_available

    - name: "Ensure wireless interfaces are disabled | Check if wifi is enabled"
      command: nmcli radio wifi
      register: rhel_nmcli_available
      changed_when: rhel_nmcli_available.stdout != "disabled"
      failed_when: false
      when: rhel_nmcli_available.rc == 0

    - name: "Ensure wireless interfaces are disabled | Disable wifi if enabled"
      command: nmcli radio all off
      changed_when: false
      failed_when: false
      when: rhel_nmcli_available is changed
  when:
    - wireless_interfaces_are_disabled

- name: "Disable IPv6"
  replace:
    dest: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!ipv6.disable=1)(?:")'
    replace: '\1"\2 ipv6.disable=1"'
    follow: true
  notify: generate new grub config
  when:
    - disable_ipv6
