---
- name: generate new grub config
  become: true
  command: grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
  notify: fix permissions after generate new grub config handler

- name: fix permissions after generate new grub config handler
  become: true
  file:
      path: "/boot/efi/EFI/redhat/grub.cfg"
      owner: root
      group: root
      mode: 0400
