project_id = "pid-gcp-tlz-gke01-d0cc"
environment = "cde"
zone = "us-east1-b"
gcp_creds = "/Users/bijjalap/Downloads/pid-gcp-tlz-gke01-d0cc-f85f2fd333d3.json"
vm_subnet = "subnet-for-packer-vms"
skip_create_image = "false"