---
# This file lists the definitions of variables used in RHEL 8 LZ golden image creation
# Based on OSCB  document at https://docs.google.com/document/d/1kgwIbmhICANOkw0-PAd8F0o69WQVsZH6aW3tTV0e_yg/edit#
# Refer to common linux definition file if any present while adding or modifying the content of this file

# Required file permissions
var_file_permissions:
  - {name: /etc/issue, mode: "0644"}  # 1.8.1.4 - 1.8.1.6
  - {name: /etc/issue.net, mode: "0644"}  # 1.8.1.4 - 1.8.1.6
  - {name: /etc/passwd, mode: "0644"}  # 6.1.2
  - {name: /etc/passwd-, mode: "u-x,go-rwx"}  # 6.1.6
  - {name: /etc/group, mode: "0644"}  # 6.1.4
  - {name: /etc/group-, mode: "u-x,go-wx"}  # 6.1.8
  - {name: /etc/shadow, mode: "o-rwx,g-wx"}  # 6.1.3
  - {name: /etc/gshadow, mode: "o-rwx,g-rw"}  # 6.1.5
  - {name: /etc/shadow-, mode: "u-x,go-rwx"}  # 6.1.7
  - {name: /etc/gshadow-, mode: "o-rwx,g-rw"}  # 6.1.9
  - {name: /boot/efi/EFI/redhat/grubenv, mode: "og-rwx"}  # 1.5.1
  - {name: /boot/efi/EFI/redhat/grub.cfg, mode: "og-rwx"}  # 1.5.1
  - {name: /etc/ssh/sshd_config, mode: "og-rwx"}

# Prefix string to be used to identify X11 packages
x11_package_prefix: xorg-x11

# Applicable remote login warning banner files
login_warning_banner_files:
  - /etc/issue.net
  - /etc/issue

# Banner files to be removed
login_warning_banner_remove_files:

# 5.2.2 - 5.2.19 Ensure SSH Protocol is configured
# no config to add or modify from the base_sshd_config
additional_sshd_config:
  - {regex: '^MaxSessions', value: 'MaxSessions 4'}  # CIS 5.2.19

# List of services to be disabled
# Verify name of the service using' systemctl list-units --type=service' on unhardened instance
disable_services:
  - {service_name: rsyncd, package_name: rsyncd}  # 2.2.3 Ensure rsync service is not enabled
  - {service_name: smb, package_name: samba}  # 2.2.7 Ensure Samba is not enabled
  - {service_name: vsftpd, package_name: vsftpd}  # 2.2.10 Ensure FTP Server is not enabled
  - {service_name: nfs-server, package_name: nfs-utils}  # 2.2.12 Ensure NFS is not enabled
  - {service_name: autofs, package_name: autofs}  # 1.1.22 Disable Auto mounting
  - {service_name: firewalld, package_name: firewalld}  # 3.4 Ensure Firewalld disabled
  - {service_name: nftables, package_name: nftables}  #  Ensure nftables disabled

# 2.2.1.2 Ensure chrony is configured
# no config to add or modify from the base_chrony_content
additional_chrony_content:
