---
# This file lists the definitions of variables used in RHEL 7 LZ golden image creation
# Based on MSB document at https://docs.google.com/document/d/1pkGWA_nwJUZCZZTxNaHgCzW0RMlSwyqgz4sn_5aIJOg/edit#
# Refer to common linux definition file if any present while adding or modifying the content of this file

# Required file permissions
var_file_permissions:
  - {name: /etc/passwd, mode: "0644"}  # 6.1.2
  - {name: /etc/passwd-, mode: "og-rw"}  # 6.1.6
  - {name: /etc/group, mode: "0644"}  # 6.1.4
  - {name: /etc/group-, mode: "og-rw"}  # 6.1.8
  - {name: /etc/shadow, mode: "og-rw"}   # 6.1.3
  - {name: /etc/gshadow, mode: "og-rw"}  # 6.1.5
  - {name: /etc/shadow-, mode: "og-rw"}  # 6.1.7
  - {name: /etc/gshadow-, mode: "og-rw"}  # 6.1.9
  - {name: /etc/ssh/sshd_config, mode: "og-rwx"}
  - {name: /boot/grub2/grub.cfg, mode: "og-rwx"}
  - {name: /boot/efi/EFI/redhat/grub.cfg, mode: "og-rwx"}

# Applicable remote login warning banner files
login_warning_banner_files:
  - /etc/issue

# Banner files to be removed
login_warning_banner_remove_files:
  - /etc/issue.net

# Prefix string to be used to identify X11 packages
x11_package_prefix: xorg-x11

# 5.2.2 - 5.2.19 Ensure SSH Protocol is configured
# sshd configuration to be added or modified from/to the base_sshd_config
additional_sshd_config:
  - {regex: '^GSSAPICleanupCredentials', value: 'GSSAPICleanupCredentials yes'}
  - {regex: '^MACs', value: 'MACs hmac-sha1,hmac-ripemd160'}
  - {regex: '^ClientAliveInterval', value: 'ClientAliveInterval 300'}  # CIS 5.2.13
  - {regex: '^ClientAliveCountMax', value: 'ClientAliveCountMax 0'}  # CIS 5.2.13

# List of services to be disabled
# Verify name of the service using 'systemctl list-units --type=service' on unhardened instance
# and package names using 'yum list installed'
disable_services:
  - {service_name: firewalld, package_name: firewalld}  # Ensure Firewalld disabled
  - {service_name: NetworkManager, package_name: NetworkManager}  # Disable Network Manager

# 2.2.1.2 Ensure chrony is configured
# Additional content to be added or modified from/to the base_chrony_content
additional_chrony_content:
  - {regex: '^stratumweight', value: 'stratumweight 0'}  # ignore stratum when selecting the source
  - {regex: '^rtcsync', value: 'rtcsync'}
  - {regex: '^keyfile', value: 'keyfile /etc/chrony.keys'}
  - {regex: '^commandkey', value: 'commandkey 1'}  # Command key number 1 i.e., ex: SHA1
  - {regex: '^generatecommandkey', value: 'generatecommandkey'}
  - {regex: '^bindcmdaddress', value: "bindcmdaddress 127.0.0.1 \nbindcmdaddress ::1"}
  - {regex: '^noclientlog', value: 'noclientlog'}
  - {regex: '^logchange', value: 'logchange 0.5'}
