---
- name: Account logon, credential validation
  win_audit_policy_system:
    subcategory: "{{ item.subcategory }}"
    audit_type: "{{ item.audit_type }}"
  loop: "{{ audit_policy_subcategories }}"
  tags:
    - audit_policy
