---
- name: Disable ssl 3.0 client
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Client"
    data: "{{ enable_ssl_3_0_client }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - ssl_3.0

- name: Disable ssl 3.0 server
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server"
    data: "{{ enable_ssl_3_0_server }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - ssl_3.0

- name: Disable TLS 1.0 Server
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server"
    data: "{{ enable_tls_1_0_server }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - tls1

- name: Disable TLS 1.0 Client
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server"
    data: "{{ enable_tls_1_0_client }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - tls1

- name: Disable TLS 1.1 Server
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server"
    data: "{{ enable_tls_1_1_server }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - tls

- name: Disable TLS 1.1 Client
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Client"
    data: "{{ enable_tls_1_1_client }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - tls

- name: Disable RC4 128
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128"
    data: "{{ enable_rc4_128 }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - RC4

- name: Disable RC4 40
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 40/128"
    data: "{{ enable_rc4_40 }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - RC4

- name: Disable RC4 56
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 56/128"
    data: "{{ enable_rc4_56 }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - RC4

- name: Disable RC4 64
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 64/128"
    data: "{{ enable_rc4_64 }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - RC4

- name: Disable RC2 128
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC2 128/128"
    data: "{{ enable_rc2_128 }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - RC2

- name: Disable RC2 40
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC2 40/128"
    data: "{{ enable_rc2_40 }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - RC2

- name: Disable RC2 56
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC2 56/128"
    data: "{{ enable_rc2_56 }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - RC2

- name: Disable DES 56
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC2 56/56"
    data: "{{ enable_des_56 }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - DES

- name: Disable Triple DES
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\Triple DES 168"
    data: "{{ enable_triple_des }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - DES

- name: Disable SSL 2.0 Client
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\Client"
    data: "{{ enable_ssl_2_0_client }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - SSL

- name: Disable SSL 2.0 Server
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\Server"
    data: "{{ enable_ssl_2_0_server }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - SSL

- name: Disable Diffie-Hellman
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\KeyExchangeAlgorithms\\Diffie-Hellman"
    data: "{{ enable_diffie_hellman }}"
    type: dword
    name: "Enabled"
  tags:
    - cypher_policies
    - registry
    - diffie-hellman

- name: Disable SMBv1
  win_regedit:
    path: "HKLM:\\System\\CurrentControlSet\\Services\\LanmanServer\\Parameters"
    data: "{{ disable_smbv1 }}"
    type: dword
    name: "SMB1"
  tags:
    - cypher_policies
    - registry
    - smb

- name: SSL Ciphers
  win_regedit:
    path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Cryptography\\Configuration\\SSL\\00010002"
    data: "{{ ssl_ciphers }}"
    type: string
    name: "Functions"
  tags:
    - cypher_policies
    - registry
    - SSL
