---
## 1.1.1 - Account Policies: Enforce Password History
- name: Enforce password history (1.1.1)
  win_security_policy:
    section: System Access
    key: PasswordHistorySize
    value: "{{ enforce_password_history }}"
  tags:
    - password_policy
    - password_history

## 1.1.2 - Account Policies: Maximum Password Age
- name: Enforce password age (1.1.2)
  win_security_policy:
    section: System Access
    key: MaximumPasswordAge
    value: "{{ maximum_password_age }}"
  tags:
    - password_policy
    - password_max_age

## 1.1.3 - Account Policies: Minimum Password Age
- name: Enforce minimum password age (1.1.3)
  win_security_policy:
    section: System Access
    key: MinimumPasswordAge
    value: "{{ minimum_password_age }}"
  tags:
    - password_policy
    - password_min_age

## 1.1.4 - Account Policies: Minimum Password Length
- name: Enforce minimum password length (1.1.4)
  win_security_policy:
    section: System Access
    key: MinimumPasswordLength
    value: "{{ minimum_password_length[execution_type] }}"
  tags:
    - password_policy
    - password_min_length

## 1.1.5 - Account Policies: Password Complexity
- name: Enforce password complexity (1.1.5)
  win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: "{{ password_must_meet_complexity_requirements }}"
  tags:
    - password_policy
    - password_complexity

## 1.1.6 - Account Policies: Reverse encryption
- name: Store Passwords Using Reverse encryption (1.1.6)
  win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: "{{ store_passwords_using_reversible_encryption }}"
  tags:
    - password_policy
    - password_reverse_encryption

## 1.2.2 - Account Lockout: Account Lockout Threshold
- name: Account Lockout Threshold (1.2.2)
  win_security_policy:
    section: System Access
    key: LockoutBadCount
    value: "{{ account_lockout_threshold }}"
  tags:
    - password_policy
    - password_lockout_threshold

## 1.2.1 - Account Lockout: Account Lockout Duration
- name: Account Lockout Duration (1.2.1)
  win_security_policy:
    section: System Access
    key: LockoutDuration
    value: "{{  account_lockout_duration[execution_type] }}"
  tags:
    - password_policy
    - password_reverse_encryption

## 1.2.3 - Account Lockout: Reset account lockout counter after
- name: Reset Account Lockout Counter (1.2.3)
  win_security_policy:
    section: System Access
    key: ResetLockoutCount
    value: "{{ reset_account_lockout_counter_after }}"
  tags:
    - password_policy
    - password_lockout_counter

- name: Rename guest account (2.3.1.6)
  win_security_policy:
    section: System Access
    key: NewGuestName
    value: "{{ accounts_rename_guest_account[execution_type] }}"
  tags:
    - password_policy
    - password_rename_guest_account

- name: Disable Administrator account (2.3.1.1)
  win_security_policy:
    section: System Access
    key: EnableAdminAccount
    value: "{{ accounts_administrator_account_status[execution_type] }}"
  when:
    execution_type != 'gcp_image'
  tags:
    - password_policy
    - password_rename_guest_account

- name: disable guest account (2.3.1.3)
  win_security_policy:
    section: System Access
    key: EnableGuestAccount
    value: "{{ accounts_guest_account_status }}"
  tags:
    - password_policy
    - password_rename_guest_account

- name: Rename Administrator account (2.3.1.5)
  win_security_policy:
    section: System Access
    key: NewAdministratorName
    value: "{{ accounts_rename_administrator_account[execution_type] }}"
  tags:
    - password_policy
    - password_rename_admin_account
